name: argilla

dependencies:
  - python~=3.9.7
  - argilla>=1.20.0
  - pip>=2.22.0
  - pip:
      # code formatting
      - pre-commit~=3.2.0
      # extra test dependencies
      - datasets>1.17.0,!= 2.3.2 # TODO: push_to_hub fails up to 2.3.2, check patches when they come out eventually
      - huggingface_hub>=0.5.0
      - spacy==3.5.3
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0.tar.gz
      - spacy-transformers>=1.2.5
      - spacy-huggingface-hub >= 0.0.10
      - transformers[torch]>=4.30.0 # <- required for DPO with TRL
      - evaluate
      - seqeval
      - setfit>=0.7.0,<1.0.0
      - span_marker
      - openai>=0.27.10,<1.0.0
      - peft
      - trl>=0.5.0
      - sentence-transformers
      - rich!=13.1.0
      - textdescriptives>=2.7.0,<3.0.0
      - ipynbname>=2023.2.0.0